"""initial

Revision ID: ec21ea6bd62f
Revises: 
Create Date: 2026-06-01 09:34:32.324045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec21ea6bd62f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_sid', sa.String(length=64), nullable=False),
    sa.Column('caller', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('duration_secs', sa.Float(), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_call_sid'), 'calls', ['call_sid'], unique=True)
    op.create_index(op.f('ix_calls_caller'), 'calls', ['caller'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_caller'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_sid'), table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
